ccmake . -Wno-dev \
      -DCMAKE_INSTALL_PREFIX=/home/scms/fucf/works/wanzongliang/gromacs-2022.5/build \
      -DCMAKE_CXX_COMPILER=/opt/gnu/gcc/11.2.0/bin/g++ \
      -DCMAKE_C_COMPILER=/opt/gnu/gcc/11.2.0/bin/gcc \
      -DGMX_FFT_LIBRARY=fftw3 \
      -DFFTWF_INCLUDE_DIR=/home/scms/fucf/opt/fftw/3.3.10-gcc-11.2.0/include \
      -DFFTWF_LIBRARY=/home/scms/fucf/opt/fftw/3.3.10-gcc-11.2.0/lib/libfftw3f.a \
      -DGMX_SIMD=SSE4.1 \
      -DGMX_DEFAULT_SUFFIX=OFF \
      -DGMX_BINARY_SUFFIX=-2022.5 \
      -DGMX_LIBS_SUFFIX=-2022.5 \
      -DGMX_PREFER_STATIC_LIBS=ON \
      -DBUILD_SHARED_LIBS=OFF \
      -DGMX_BUILD_SHARED_EXE=OFF \
      -DGMX_DOUBLE=OFF \
      -DGMX_MPI=OFF \
      -DGMX_THREAD_MPI=ON \
      -DGMX_OPENMP=ON \
      -DGMX_GSL=ON \
      -DGMX_EXTERNAL_BLAS=OFF \
      -DGMX_EXTERNAL_LAPACK=OFF \
      -DGMX_GPU=OFF \
      -DGMX_DETECT_GPU_AVAILABLE=OFF \
      -DCMAKE_PREFIX_PATH=/usr
#      -DBUILD_SHARED_LIBS=ON \
#      -DGMX_BUILD_MANUAL=ON \
#      -DGMX_LOAD_PLUGINS=ON \
#      -DGMX_VMD_PLUGIN_PATH=/home/cffu/opt/vmd/plugins/compile/lib_LINUXAMD64/molfile \
#      -DGMX_FFT_LIBRARY=fftw3 \
#      -DFFTWF_INCLUDE_DIR=/home/cffu/opt/fftw/3.3.8-gnu9-avx/include \
#      -DFFTWF_LIBRARY=/home/cffu/opt/fftw/3.3.8-gnu9-avx/lib/libfftw3f.a \

cmake . -DCMAKE_INSTALL_PREFIX=/home/u2023110661/app/gromacs/gromacs-2022.5-mpi/gromacs-2022.5/build \
      -DCMAKE_CXX_COMPILER=/opt/app/openmpi/4.1.4/bin/mpicxx \
      -DCMAKE_C_COMPILER=/opt/app/openmpi/4.1.4/bin/mpicc \
      -DGMX_PREFER_STATIC_LIBS=ON \
      -DBUILD_SHARED_LIBS=OFF \
      -DGMX_BUILD_SHARED_EXE=OFF \
      -DGMX_BUILD_OWN_FFTW=ON \
      -DGMX_SIMD=AVX_256 \
      -DGMX_DEFAULT_SUFFIX=OFF \
      -DGMX_BINARY_SUFFIX=-2022.5-mpi \
      -DGMX_LIBS_SUFFIX=-2022.5-mpi \
      -DGMX_DOUBLE=OFF \
      -DGMX_MPI=ON \
      -DGMX_THREAD_MPI=OFF \
      -DGMX_OPENMP=ON \
      -DGMX_GSL=ON \
      -DGMX_LOAD_PLUGINS=OFF \
      -DGMX_EXTERNAL_BLAS=OFF \
      -DGMX_EXTERNAL_LAPACK=OFF \
      -DGMX_GPU=OFF \
      -DGMX_DETECT_GPU_AVAILABLE=OFF \
      -DCMAKE_PREFIX_PATH=/usr


cmake . -DCMAKE_INSTALL_PREFIX=/home/wzl/gromacs-2024.1/build \
      -DGMX_BUILD_OWN_FFTW=ON \
      -DGMX_SIMD=SSE4.1 \
      -DGMX_DEFAULT_SUFFIX=OFF \
      -DGMX_BINARY_SUFFIX=-2024.1 \
      -DGMX_LIBS_SUFFIX=-2024.1 \
      -DGMX_PREFER_STATIC_LIBS=ON \
      -DBUILD_SHARED_LIBS=OFF \
      -DGMX_BUILD_SHARED_EXE=OFF \
      -DGMX_DOUBLE=OFF \
      -DGMX_MPI=OFF \
      -DGMX_THREAD_MPI=ON \
      -DGMX_OPENMP=ON \
      -DGMX_GSL=ON \
      -DGMX_EXTERNAL_BLAS=OFF \
      -DGMX_EXTERNAL_LAPACK=OFF \
      -DGMX_GPU=OFF \
      -DGMX_DETECT_GPU_AVAILABLE=OFF \
      -DCMAKE_PREFIX_PATH=/usr
